apiVersion: v1
kind: Secret
metadata:
  name: snap-stack-storage-secret # Name of the Secret within the Kubernetes cluster
type: Opaque # Default Secret type used when no specific type is provided
stringData: 
  azurestorageaccountname: snapstackstorage # Azure Storage Account name
  azurestorageaccountkey: "Dummy" # Access key for the Azure Storage Account